plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.4'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java-library'
    id 'maven-publish'
    id "com.vanniktech.maven.publish" version "0.32.0"
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            versionMapping {
                allVariants {
                    fromResolutionResult()
                }
            }
        }
    }
}

group = 'io.github.danburen'
version = '0.0.1'
description = 'spring-launch-monitor'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(22)
    }
    withJavadocJar()
    withSourcesJar()
}

bootJar { enabled = false }
jar { enabled = true }

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'

    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    runtimeOnly 'org.yaml:snakeyaml'

    testCompileOnly 'org.projectlombok:lombok:1.18.36'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.36'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'com.mysql:mysql-connector-j'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

mavenPublishing {
    publishToMavenCentral("CENTRAL_PORTAL")

    signAllPublications()

    coordinates(group, "spring-launch-monitor", version)

    pom {
        name = "Spring Launch Monitor"
        description = "A plug-and-play Spring Boot startup profiler that instantly pinpoints slow startup bottlenecks."
        inceptionYear = "2026"
        url = "https://github.com/danburen/spring-launch-monitor"

        licenses {
            license {
                name = "MIT License"
                url = "https://opensource.org/license/MIT"
                distribution = "repo"
            }
        }

        developers {
            developer {
                id = "danburen"
                name = "Cong Huang"
                email = "huang.cong0210@qq.com"
            }
        }

        scm {
            url = "https://github.com/danburen/spring-launch-monitor"
            connection = "scm:git:https://github.com/danburen/spring-launch-monitor.git"
            developerConnection = "scm:git:https://github.com/danburen/spring-launch-monitor.git"
        }
    }
}